export const TAROT_CARD_DETAILS = {
    major: [
        { id: 0, name: "Deli", meaning: "Yeni başlangıçlar, masumiyet, kendiliğindenlik ve tamamen özgür bir ruh.", element: "Hava", astrology: "Uranüs", timing: "Aniden / Beklenmedik", numerology: "0", yesNo: "Evet" },
        { id: 1, name: "Büyücü", meaning: "Yaratıcılık, beceri, odaklanma ve arzuları tezahür ettirme gücü.", element: "Hava", astrology: "Merkür", timing: "Hızlı / Sürekli", numerology: "1", yesNo: "Evet" },
        { id: 2, name: "Azize", meaning: "Sezgi, gizem, bilinçaltı ve içsel bilgelik.", element: "Su", astrology: "Ay", timing: "Dolunay / Bekleme", numerology: "2", yesNo: "Belki" },
        { id: 3, name: "İmparatoriçe", meaning: "Bereket, annelik, doğanın cömertliği ve yaratıcı dişillik.", element: "Toprak", astrology: "Venüs", timing: "Cuma / Mayıs / Bahar", numerology: "3", yesNo: "Evet" },
        { id: 4, name: "İmparator", meaning: "Otorite, yapı, disiplin ve rasyonel zihin.", element: "Ateş", astrology: "Koç", timing: "Mart-Nisan / İlkbahar", numerology: "4", yesNo: "Evet" },
        { id: 5, name: "Aziz", meaning: "Gelenek, ruhani rehberlik, inanç ve toplumsal değerler.", element: "Toprak", astrology: "Boğa", timing: "Nisan-Mayıs / Bahar", numerology: "5", yesNo: "Belki" },
        { id: 6, name: "Aşıklar", meaning: "Aşk, uyum, derin ilişkiler ve önemli seçimler.", element: "Hava", astrology: "İkizler", timing: "Mayıs-Haziran / Geç Bahar", numerology: "6", yesNo: "Evet" },
        { id: 7, name: "Araba", meaning: "Kontrol, irade gücü, zafer ve kararlılık.", element: "Su", astrology: "Yengeç", timing: "Haziran-Temmuz / Yaz", numerology: "7", yesNo: "Evet" },
        { id: 8, name: "Güç", meaning: "İçsel güç, sabır, şefkat ve cesaret.", element: "Ateş", astrology: "Aslan", timing: "Temmuz-Ağustos / Yaz", numerology: "8", yesNo: "Evet" },
        { id: 9, name: "Ermiş", meaning: "İç gözlem, yalnızlık, ruhsal rehberlik ve gerçeği arayış.", element: "Toprak", astrology: "Başak", timing: "Ağustos-Eylül / Geç Yaz", numerology: "9", yesNo: "Belki" },
        { id: 10, name: "Kader Çarkı", meaning: "Değişim, şans, kaderin döngüsü ve dönüm noktaları.", element: "Ateş", astrology: "Jüpiter", timing: "Hızlı Değişim / Perşembe", numerology: "10", yesNo: "Evet" },
        { id: 11, name: "Adalet", meaning: "Hakkaniyet, dürüstlük, sebep-sonuç ilişkisi ve yasal denge.", element: "Hava", astrology: "Terazi", timing: "Eylül-Ekim / Sonbahar", numerology: "11", yesNo: "Evet" },
        { id: 12, name: "Asılan Adam", meaning: "Farklı bir bakış açısı, bilinçli duraklama ve fedakarlık.", element: "Su", astrology: "Neptün", timing: "Beklenmedik Duraklama", numerology: "12", yesNo: "Belki" },
        { id: 13, name: "Ölüm", meaning: "Dönüşüm, sonlanma ve yeni başlangıçlar.", element: "Su", astrology: "Akrep", timing: "Ekim-Kasım / Sonbahar", numerology: "13", yesNo: "Hayır" },
        { id: 14, name: "Denge", meaning: "Uyum, sabır, ılımlılık ve zıtlıkların birleşimi.", element: "Ateş", astrology: "Yay", timing: "Kasım-Aralık / Geç Güz", numerology: "14", yesNo: "Evet" },
        { id: 15, name: "Şeytan", meaning: "Bağımlılık, maddiyatçı kısıtlamalar ve gölge yanlar.", element: "Toprak", astrology: "Oğlak", timing: "Aralık-Ocak / Kış", numerology: "15", yesNo: "Hayır" },
        { id: 16, name: "Yıkılan Kule", meaning: "Ani yıkım, sarsıcı değişim ve aydınlanma.", element: "Ateş", astrology: "Mars", timing: "Salı / Aniden", numerology: "16", yesNo: "Hayır" },
        { id: 17, name: "Yıldız", meaning: "Umut, ilham, yenilenme ve ruhsal ferahlama.", element: "Hava", astrology: "Kova", timing: "Ocak-Şubat / Kış", numerology: "17", yesNo: "Evet" },
        { id: 18, name: "Ay", meaning: "İlüzyon, korku, bilinçaltı rehberliği ve belirsizlik.", element: "Su", astrology: "Balık", timing: "Şubat-Mart / Geç Kış", numerology: "18", yesNo: "Belki" },
        { id: 19, name: "Güneş", meaning: "Mutlak başarı, neşe, canlılık ve özgüven.", element: "Ateş", astrology: "Güneş", timing: "Pazar / Yaz Gündönümü", numerology: "19", yesNo: "Evet" },
        { id: 20, name: "Mahkeme", meaning: "Uyanış, değerlendirme ve yaşam amacının keşfi.", element: "Ateş", astrology: "Plüton", timing: "Sonuçlanma / Aniden", numerology: "20", yesNo: "Evet" },
        { id: 21, name: "Dünya", meaning: "Tamamlanma, başarı, bütünlük ve seyahat.", element: "Toprak", astrology: "Satürn", timing: "Cumartesi / Başarı", numerology: "21", yesNo: "Evet" }
    ],
    wands: [
        { id: 22, name: "Değnek Ası", meaning: "İlham, tutku ve yaratıcı kıvılcım. Yeni bir başlangıç.", element: "Ateş", astrology: "Ateş", timing: "İlkbahar / Günler", numerology: "1", yesNo: "Evet" },
        { id: 23, name: "Değnek İkilisi", meaning: "Planlama, kararlar ve gelecek vizyonu.", element: "Ateş", astrology: "Mars/Koç", timing: "2-10 Gün", numerology: "2", yesNo: "Evet" },
        { id: 24, name: "Değnek Üçlüsü", meaning: "Bekleyiş, genişleme ve ufukta görünen başarı.", element: "Ateş", astrology: "Güneş/Koç", timing: "3-10 Gün", numerology: "3", yesNo: "Evet" },
        { id: 25, name: "Değnek Dörtlüsü", meaning: "Kutlama, yuva huzuru ve istikrar.", element: "Ateş", astrology: "Venüs/Koç", timing: "4-10 Gün", numerology: "4", yesNo: "Evet" },
        { id: 26, name: "Değnek Beşlisi", meaning: "Rekabet, fikir ayrılıkları ve çatışmalar.", element: "Ateş", astrology: "Satürn/Aslan", timing: "5-10 Gün", numerology: "5", yesNo: "Hayır" },
        { id: 27, name: "Değnek Altılısı", meaning: "Zafer, tanınma ve hak edilen başarı.", element: "Ateş", astrology: "Jüpiter/Aslan", timing: "6-10 Gün", numerology: "6", yesNo: "Evet" },
        { id: 28, name: "Değnek Yedilisi", meaning: "Savunma, azim ve pozisyonunu koruma.", element: "Ateş", astrology: "Mars/Aslan", timing: "7-10 Gün", numerology: "7", yesNo: "Evet" },
        { id: 29, name: "Değnek Sekizlisi", meaning: "Hız, ani haberler ve beklenen gelişmeler.", element: "Ateş", astrology: "Merkür/Yay", timing: "8-10 Gün / Hızlı", numerology: "8", yesNo: "Evet" },
        { id: 30, name: "Değnek Dokuzlusu", meaning: "Son direnç, koruma ve yorgunluk.", element: "Ateş", astrology: "Ay/Yay", timing: "9-10 Gün", numerology: "9", yesNo: "Belki" },
        { id: 31, name: "Değnek Onlusu", meaning: "Ağır sorumluluklar, yük taşıma ve stres.", element: "Ateş", astrology: "Satürn/Yay", timing: "10 Gün / Son", numerology: "10", yesNo: "Hayır" },
        { id: 32, name: "Değnek Prensi", meaning: "Maceracı ruh, cesur haberler ve keşif tutkusu.", element: "Ateş", astrology: "Toprak/Ateş", timing: "Bahar / Hızlı", numerology: "Sayfa", yesNo: "Evet" },
        { id: 33, name: "Değnek Şövalyesi", meaning: "Tutkulu eylem, sabırsızlık ve cesaret.", element: "Ateş", astrology: "Hava/Ateş", timing: "Bahar / Çok Hızlı", numerology: "Şövalye", yesNo: "Evet" },
        { id: 34, name: "Değnek Kraliçesi", meaning: "Özgüven, çekicilik ve sosyal güç.", element: "Ateş", astrology: "Su/Ateş", timing: "Bahar / Sabit", numerology: "Kraliçe", yesNo: "Evet" },
        { id: 35, name: "Değnek Kralı", meaning: "Vizyoner liderlik ve girişimci güç.", element: "Ateş", astrology: "Ateş/Ateş", timing: "Bahar / Otorite", numerology: "Kral", yesNo: "Evet" }
    ],
    cups: [
        { id: 36, name: "Kupa Ası", meaning: "Yeni duygular, aşkın doğuşu ve ruhsal doluluk.", element: "Su", astrology: "Su", timing: "Yaz / Haftalar", numerology: "1", yesNo: "Evet" },
        { id: 37, name: "Kupa İkilisi", meaning: "Derin bağlantı, romantizm ve uyum.", element: "Su", astrology: "Venüs/Yengeç", timing: "2-10 Hafta", numerology: "2", yesNo: "Evet" },
        { id: 38, name: "Kupa Üçlüsü", meaning: "Paylaşılan mutluluk, dostluk ve kutlama.", element: "Su", astrology: "Merkür/Yengeç", timing: "3-10 Hafta", numerology: "3", yesNo: "Evet" },
        { id: 39, name: "Kupa Dörtlüsü", meaning: "İlgisizlik, can sıkıntısı ve fırsatları kaçırma.", element: "Su", astrology: "Ay/Yengeç", timing: "4-10 Hafta", numerology: "4", yesNo: "Belki" },
        { id: 40, name: "Kupa Beşlisi", meaning: "Hüzün, pişmanlık ve kayba odaklanma.", element: "Su", astrology: "Mars/Akrep", timing: "5-10 Hafta", numerology: "5", yesNo: "Hayır" },
        { id: 41, name: "Kupa Altılısı", meaning: "Nostalji, geçmiş anılar ve masumiyet.", element: "Su", astrology: "Güneş/Akrep", timing: "6-10 Hafta", numerology: "6", yesNo: "Evet" },
        { id: 42, name: "Kupa Yedilisi", meaning: "Hayaller, sanrılar ve kafa karışıklığı.", element: "Su", astrology: "Venüs/Akrep", timing: "7-10 Hafta", numerology: "7", yesNo: "Belki" },
        { id: 43, name: "Kupa Sekizlisi", meaning: "Duygusal terk ediş ve manevi yolculuk.", element: "Su", astrology: "Satürn/Balık", timing: "8-10 Hafta", numerology: "8", yesNo: "Hayır" },
        { id: 44, name: "Kupa Dokuzlusu", meaning: "Duygusal tatmin ve dileklerin kabulü.", element: "Su", astrology: "Jüpiter/Balık", timing: "9-10 Hafta", numerology: "9", yesNo: "Evet" },
        { id: 45, name: "Kupa Onlusu", meaning: "Mutlu aile hayatı ve sevgi dolu yuva.", element: "Su", astrology: "Mars/Balık", timing: "10 Hafta", numerology: "10", yesNo: "Evet" },
        { id: 46, name: "Kupa Prensi", meaning: "Hassas mesajlar ve sanatsal ilham.", element: "Su", astrology: "Toprak/Su", timing: "Yaz / Akıcı", numerology: "Sayfa", yesNo: "Evet" },
        { id: 47, name: "Kupa Şövalyesi", meaning: "Duygusal teklifler ve romantik jestler.", element: "Su", astrology: "Hava/Su", timing: "Yaz / Hızlı", numerology: "Şövalye", yesNo: "Evet" },
        { id: 48, name: "Kupa Kraliçesi", meaning: "Sezgisellik ve derin empati.", element: "Su", astrology: "Su/Su", timing: "Yaz / Derin", numerology: "Kraliçe", yesNo: "Evet" },
        { id: 49, name: "Kupa Kralı", meaning: "Duygusal denge ve diplomatik bilgelik.", element: "Su", astrology: "Ateş/Su", timing: "Yaz / Hakim", numerology: "Kral", yesNo: "Evet" }
    ],
    swords: [
        { id: 50, name: "Kılıç Ası", meaning: "Zihinsel netlik, gerçekler ve keskin zeka.", element: "Hava", astrology: "Hava", timing: "Sonbahar / Aylar", numerology: "1", yesNo: "Evet" },
        { id: 51, name: "Kılıç İkilisi", meaning: "Çıkmaz sokak ve kararsızlık.", element: "Hava", astrology: "Ay/Terazi", timing: "2-10 Ay", numerology: "2", yesNo: "Belki" },
        { id: 52, name: "Kılıç Üçlüsü", meaning: "Kalp kırıklığı ve zihinsel acı.", element: "Hava", astrology: "Satürn/Terazi", timing: "3-10 Ay", numerology: "3", yesNo: "Hayır" },
        { id: 53, name: "Kılıç Dörtlüsü", meaning: "Zihinsel dinlenme ve meditasyon vakti.", element: "Hava", astrology: "Jüpiter/Terazi", timing: "4-10 Ay", numerology: "4", yesNo: "Evet (Dinlenme)" },
        { id: 54, name: "Kılıç Beşlisi", meaning: "Kazanırken kaybetmek ve çatışma.", element: "Hava", astrology: "Venüs/Kova", timing: "5-10 Ay", numerology: "5", yesNo: "Hayır" },
        { id: 55, name: "Kılıç Altılısı", meaning: "Zorlukları geride bırakma ve şifa.", element: "Hava", astrology: "Merkür/Kova", timing: "6-10 Ay", numerology: "6", yesNo: "Evet" },
        { id: 56, name: "Kılıç Yedilisi", meaning: "Strateji, gizlilik ve kurnazlık.", element: "Hava", astrology: "Ay/Kova", timing: "7-10 Ay", numerology: "7", yesNo: "Belki" },
        { id: 57, name: "Kılıç Sekizlisi", meaning: "Engellenmişlik hissi ve korku.", element: "Hava", astrology: "Jüpiter/İkizler", timing: "8-10 Ay", numerology: "8", yesNo: "Hayır" },
        { id: 58, name: "Kılıç Dokuzlusu", meaning: "Endişe ve uykusuz geceler.", element: "Hava", astrology: "Mars/İkizler", timing: "9-10 Ay", numerology: "9", yesNo: "Hayır" },
        { id: 59, name: "Kılıç Onlusu", meaning: "Tam bir sonlanma ve ihanet.", element: "Hava", astrology: "Güneş/İkizler", timing: "10 Ay", numerology: "10", yesNo: "Hayır" },
        { id: 60, name: "Kılıç Prensi", meaning: "Merak ve zihinsel uyanış.", element: "Hava", astrology: "Toprak/Hava", timing: "Sonbahar / Keskin", numerology: "Sayfa", yesNo: "Hayır" },
        { id: 61, name: "Kılıç Şövalyesi", meaning: "Kararlılık ve hızlı aksiyon.", element: "Hava", astrology: "Hava/Hava", timing: "Sonbahar / Çok Hızlı", numerology: "Şövalye", yesNo: "Evet" },
        { id: 62, name: "Kılıç Kraliçesi", meaning: "Bağımsızlık ve dürüstlük.", element: "Hava", astrology: "Su/Hava", timing: "Sonbahar / Net", numerology: "Kraliçe", yesNo: "Evet" },
        { id: 63, name: "Kılıç Kralı", meaning: "Entelektüel otorite ve adalet.", element: "Hava", astrology: "Ateş/Hava", timing: "Sonbahar / Stratejik", numerology: "Kral", yesNo: "Evet" }
    ],
    pentacles: [
        { id: 64, name: "Tılsım Ası", meaning: "Maddi fırsatlar ve fiziksel bolluk.", element: "Toprak", astrology: "Toprak", timing: "Kış / Mevsimler", numerology: "1", yesNo: "Evet" },
        { id: 65, name: "Tılsım İkilisi", meaning: "Öncelikleri dengeleme ve esneklik.", element: "Toprak", astrology: "Jüpiter/Oğlak", timing: "2-10 Ay / Sezon", numerology: "2", yesNo: "Belki" },
        { id: 66, name: "Tılsım Üçlüsü", meaning: "İşbirliği ve yeteneklerin takdiri.", element: "Toprak", astrology: "Mars/Oğlak", timing: "3-10 Ay", numerology: "3", yesNo: "Evet" },
        { id: 67, name: "Tılsım Dörtlüsü", meaning: "Güven arayışı ve birikim yapma.", element: "Toprak", astrology: "Güneş/Oğlak", timing: "4-10 Ay", numerology: "4", yesNo: "Evet (Koruma)" },
        { id: 68, name: "Tılsım Beşlisi", meaning: "Maddi zorluklar ve izolasyon.", element: "Toprak", astrology: "Merkür/Boğa", timing: "5-10 Ay", numerology: "5", yesNo: "Hayır" },
        { id: 69, name: "Tılsım Altılısı", meaning: "Cömertlik ve hakkaniyetli paylaşım.", element: "Toprak", astrology: "Ay/Boğa", timing: "6-10 Ay", numerology: "6", yesNo: "Evet" },
        { id: 70, name: "Tılsım Yedilisi", meaning: "Sabır ve emeğin meyvelerini bekleme.", element: "Toprak", astrology: "Satürn/Boğa", timing: "7-10 Ay", numerology: "7", yesNo: "Belki" },
        { id: 71, name: "Tılsım Sekizlisi", meaning: "Çok çalışma ve uzmanlık.", element: "Toprak", astrology: "Güneş/Başak", timing: "8-10 Ay", numerology: "8", yesNo: "Evet" },
        { id: 72, name: "Tılsım Dokuzlusu", meaning: "Lüks ve maddi bağımsızlık.", element: "Toprak", astrology: "Venüs/Başak", timing: "9-10 Ay", numerology: "9", yesNo: "Evet" },
        { id: 73, name: "Tılsım Onlusu", meaning: "Miras ve aile bağları.", element: "Toprak", astrology: "Merkür/Başak", timing: "10 Ay", numerology: "10", yesNo: "Evet" },
        { id: 74, name: "Tılsım Prensi", meaning: "Pratik hırs ve sadakat.", element: "Toprak", astrology: "Toprak/Toprak", timing: "Kış / Planlı", numerology: "Sayfa", yesNo: "Evet" },
        { id: 75, name: "Tılsım Şövalyesi", meaning: "Disiplin ve güvenilirlik.", element: "Toprak", astrology: "Hava/Toprak", timing: "Kış / Yavaş", numerology: "Şövalye", yesNo: "Evet" },
        { id: 76, name: "Tılsım Kraliçesi", meaning: "Güvenlik ve pratik şefkat.", element: "Toprak", astrology: "Su/Toprak", timing: "Kış / Verimli", numerology: "Kraliçe", yesNo: "Evet" },
        { id: 77, name: "Tılsım Kralı", meaning: "Finansal güç ve bereket.", element: "Toprak", astrology: "Ateş/Toprak", timing: "Kış / Hakim", numerology: "Kral", yesNo: "Evet" }
    ]
};
